name: Build and Release

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Specify the required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build project
        run: |
          python setup.py sdist bdist_wheel

      - name: Upload release assets
        uses: actions/upload-artifact@v3
        with:
          name: release-assets
          path: dist/*.tar.gz

  release:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Download built assets
        uses: actions/download-artifact@v3
        with:
          name: release-assets
          path: dist

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
