name: Build and Release

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Git
        run: |
          choco install git -y

      - name: Install Nim
        run: |
          choco install nim -y
          echo "## Adding Nim and Nimble to PATH"
          $env:PATH += ";$($env:USERPROFILE)\scoop\apps\nim\current\bin"

      - name: Verify Nim and Nimble installation
        run: |
          nim --version
          nimble --version

      - name: Install Nim requirements
        run: |
          nimble install -y nimpy nimraylib_now x11 winim

      - name: Compile Project
        run: |
          nim c pyMeow.nim

      - name: Upload release assets
        uses: actions/upload-artifact@v3
        with:
          name: release-assets
          path: pyMeow.exe # Replace with correct executable path if needed

  release:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Download built assets
        uses: actions/download-artifact@v3
        with:
          name: release-assets
          path: dist

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/pyMeow.exe" # Replace with correct executable path if needed
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
